// action常量
export const LOGIN = 'LOGIN'
export const LOGIN_AJAX_START = 'LOGIN_AJAX_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const OPEN_POPUP = 'OPEN_POPUP'
export const CLOSE_POPUP = 'CLOSE_POPUP'
export const GET_ALL_LIST = 'GET_ALL_LIST'
export const GET_ALL_LIST_SUCCESS = 'GET_ALL_LIST_SUCCESS'
export const GET_ALL_LIST_FAILED = 'GET_ALL_LIST_FAILED'
